name: Translate README

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install deep-translator

    - name: Create translation script
      run: |
        echo "from deep_translator import GoogleTranslator" > translate_readme.py
        echo "with open('README.md', 'r') as file:" >> translate_readme.py
        echo "    text = file.read()" >> translate_readme.py
        echo "translated = GoogleTranslator(source='auto', target='es').translate(text)" >> translate_readme.py
        echo "with open('README_es.md', 'w') as file:" >> translate_readme.py
        echo "    file.write(translated)" >> translate_readme.py

    - name: Run translation script
      run: |
        python translate_readme.py
    
    - name: Commit translated README
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README_es.md
        git commit -m "Auto-translated README to Spanish"
        git push
